version: '3.1'

services:
  hospital_neo4j_etl:
    build:
      context: ./hospital_neo4j_etl
    env_file:
      - .env

  chatbot_api:
    build:
      context: ./chatbot_api
    env_file:
      - .env
    depends_on:
      - hospital_neo4j_etl
    ports:
      - "8900:8900"

  chatbot_frontend:
    build:
      context: ./chatbot_frontend
    env_file:
      - .env
    ports:
      - "8501:8501"
    depends_on:
      - chatbot_api
